### ISSUE TITLE
Support more operating systems

### ISSUE THREAD

**Issue by lu-zero** [bbc/vc2hqdecode#1]
I started already to prepare some patches to take care of 
- [x] drop the `-Werror` usage (breaks horribly with clang)
- [ ] find an alternative for the __builtins to probe for cpu features (breaks non-recent clang)
- [x] use `posix_memalign` (since it works for linux and mac and freebsd) 
- [x] replace clock_gettime with gettimeofday (ditto)
- [x] make sure non-gnu binutils does not lose internal symbols (tests breaks macosx)

Is there interest in having this in the main tree?

**Comment by jamesba** [comment]
Hi,

We'd be interested in taking a look at those changes. If we were to include them in the main tree we would need you to send the patches to us under a permissive BSD-style license.

**Comment by lu-zero** [comment]
I can send you a gpg statement in this regard along the lines of:

"I agree to relicense all the contributions to the vc2hqdecode tree under any OSI compliant license BBC would relicense vc2hqdecode"

Would it work?

**Comment by jamesba** [comment]
Unfortunately we would need the submission to be made under an entirely permissive license. Your name would be listed as a contributor, but we would need the capability to later modify the code however we wished and assert copyright over the entire codebase. If we accept submissions with restrictions on their licensing then it becomes an ever-growing task to keep track of what restrictions apply to which parts of the code, and would not be practical. Our dual licensing approach (GPL + a proprietary license) is similar to that used by x264, and we want to ensure that we only maintain a single version of the code which is the same for both licenses.

**Comment by greku** [comment]
Hi James,
Do you have a contributor agreement document?
(similar to http://x264.nl/developers/Dark_Shikari/CLA4.pdf for x264)

Gregory

**Comment by jamesba** [comment]
Not currently, I've asked the relevant people to draw something suitable up.

**Comment by lu-zero** [comment]
Meanwhile I can state that I'm licensing my contributions under MIT if that helps getting them in and have more people have a look at the issues on MacOSX and FreeBSD.
Then you can pretty much do whatever you like with them.

CLA are usually quite good at hindering participation, Setting the project core as GPL+or+commercial and state that all the external contributions are accepted under the MIT license should work sort of well assuming you state it clearly in the `CONTRIBUTING.md`.

**Comment by Balakrishnan-Easwaran** [comment]
Hi,

I tried using VC2 on Linux, it was possible for me to configure and setup with autotools on Linux platform it worked quite well.
But I'm trying if this can work with Windows too. I tried installing Cygwin, MSYS, mingw etc., but I cannot set this up on windows. Because it is all shell scripts. 
What is the feasibility of using Video Codec 2 on windows platform? A short quick guide would be very much appreciated. It is actually an issue around, I can see questions about this on stackoverflow and other forums but not a proper answer that could solve this issue. 
Please provide a comment about this asap. 

Thank you very much.

**Comment by jamesba** [comment]
There’s a windows directory in the decoder repository which contains a visual studio project for building the decoder. There is currently no equivalent project for the encoder, but one could be added relatively simply by someone with experience with visual studio, and if someone did want to add that and was willing to release the changes to us under a BSD-style license then we could incorporate it into the repository. Unfortunately at the present time windows support is not something we can currently commit engineers to.

## 

James P. Weaver (né Barrett)
Research Engineer
BBC R&D North Lab,
Floor 5 Dock House, MediaCity,
M50 2LH
Tel: +44(0)30 3040-9521
e-mail: james.barrett@bbc.co.uk

**Comment by Balakrishnan-Easwaran** [comment]
Sure we'll see to it.

Thank you for the reply.

_Balakrishnan.E_

**Comment by lu-zero** [comment]
Any news on the cla?

**Comment by jamesba** [comment]
As said it's as simple as "release it to us under a BSD-style license". I can ask again about getting that stated formally.

**Comment by lu-zero** [comment]
Is it ok if I just add a `Relicense-to: MIT` tag or should I add some boilerplate such as 

"I agree to relicense this contributions to the vc2hqdecode tree under any OSI compliant license BBC would relicense vc2hqdecode, this contribution can be considered under the MIT license"

?
