### ISSUE TITLE
configure script seems to ignore CXXFLAGS

### ISSUE THREAD

**Issue by hannob** [bbc/vc2hqdecode#13]
It seems to me that your configure script doesn't honor passed compiler flags.

Test with a flag that's invalid (and thus should immediately cause make to fail):
```
./configure CXXFLAGS="-foobar"
make
```

It starts compiling and simply ignores the passed CXXFLAGS.

**Comment by jamesba** [comment]
Good catch. It used the value if --enable-debug was passed to configure, and not otherwise.
