### ISSUE TITLE
Support 12bit bitstream

### ISSUE THREAD

**Issue by lu-zero** [bbc/vc2hqdecode#7]
There is a work-in-progress patch [here](https://github.com/lu-zero/vc2hqdecode/commit/a4d3c525be84625b26dcf77ede18da03d667e83f)

I tested it with the CBR reference encoder and seems working correctly, the ConstQ encoder output seems to have problems, but I hadn't tested the 10bit so might be unrelated.

**Comment by raivisr** [comment]
I guess this can be closed now as 12bit support has been merged into master.

**Comment by jamesba** [comment]
Merged into master.
