### ISSUE TITLE
Cannot decode ConstQ generated bitstream

### ISSUE THREAD

**Issue by lu-zero** [bbc/vc2hqdecode#8]
Here the command used to generate the bitstream:

```
EncodeHQ-ConstQ -v -x 1920 -y 1080 -f 4:2:2 -l 10 -k Haar0 -d 3 -u 1 -a 2 -q 0 /var/tmp/yuv422p10-1.raw /tmp/constq10-1.vc2
```

With yuv422p10-1.raw exactly a single frame.

github does not allow to upload the zipped bitstream for some reason so I can upload somewhere if it is of help.

**Comment by jamesba** [comment]
This appears to work for me. Could you upload your original video input file and the coded stream somewhere?

**Comment by lu-zero** [comment]
The bugmail got lost till today and the laptop drive with the sample died a month ago.

I'm afraid that it was the result of the compilers in use. Let's close it assuming gcc-6 and clang-4 are good now.
